# Generated by Django 4.2.14 on 2024-07-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='accepted_challenge',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
